spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: orilore
  servlet:
    multipart:
      max-file-size: 2097152
      max-request-size: 20971520
mybatis:
  config-location: classpath:mybatis.xml    
